### ISSUE TITLE
RailGroupEditorで在線表示がページを再読み込みしないと動かない

### ISSUE THREAD

**Issue by Saqliva** [WebCTC/WebCTC-Ex#5]
IPアドレス:8080/ex/railgroupのページだと再読み込みしないと在線表示が更新されません
IPアドレス:8080のページだと再読み込みしなくても表示が更新されます
環境
KaizPatch v1.3
WebCTC Alpha v0.0.1
WebCTCEx Alpha v0.0.1

サーバー:Thermos

**Comment by Kai-Z-JP** [comment]
仕様です
あくまでEditorなので
